In [3]:
'''
Author: Juarez Monteiro
Dataset: Available in https://www.kaggle.com/abcsds/pokemon
Learning from https://www.udemy.com/python-for-data-science-and-machine-learning-bootcamp
'''
print "Let's get our hands dirty."

Let's get our hands dirty.


In [4]:
import pandas as pd
import numpy as np

In [5]:
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import StandardScaler

In [6]:
%matplotlib inline

In [7]:
# Reading the Pokémon dataset
df = pd.read_csv("Pokemon.csv")

In [8]:
# Scikit learn comes with a function that split the dataset for you.

from sklearn.cross_validation import train_test_split

In [9]:
# For this example we gonna try to classify Pokémons by their Type

X = df[['Attack', 'Defense', 'Sp. Atk', 'Sp. Def', 'Speed', 'Generation']]
y = df['Type 1']

In [10]:
# Split arrays or matrices into random train and test subsets

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=7)

In [11]:
from sklearn.tree import DecisionTreeClassifier

In [12]:
dtree = DecisionTreeClassifier()

In [13]:
dtree.fit(X_train, y_train)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None, min_samples_leaf=1,
            min_samples_split=2, min_weight_fraction_leaf=0.0,
            presort=False, random_state=None, splitter='best')

In [14]:
predictions = dtree.predict(X_test)

In [15]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

In [16]:
print confusion_matrix(y_test, predictions)
print(classification_report(y_test, predictions))
print(accuracy_score(y_test, predictions))

[[6 1 0 1 0 2 0 0 3 0 0 0 1 2 1 1 1 3]
 [2 0 1 0 0 0 1 0 0 0 0 1 2 0 0 2 0 3]
 [0 0 2 0 0 0 0 1 0 0 0 0 0 1 2 1 2 2]
 [0 0 0 1 0 0 1 1 2 1 0 2 3 0 2 0 0 0]
 [0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 1 1 1 0 0 0 0 3 0 0 1 0 1]
 [0 0 2 2 0 0 3 0 0 0 0 2 2 2 0 1 0 2]
 [1 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 1 0 0 1 0 2 0 0 1 1 0 4 0 2 0]
 [3 1 1 2 1 0 2 0 1 1 0 0 2 0 5 0 0 4]
 [0 0 2 0 0 1 0 0 0 1 0 0 3 0 1 2 1 1]
 [0 0 0 1 0 0 0 0 1 0 1 0 0 0 0 2 1 2]
 [1 0 0 1 2 1 3 0 1 4 0 3 7 0 0 1 0 2]
 [0 0 0 0 0 0 1 0 0 1 0 0 1 1 0 0 0 0]
 [2 0 1 0 2 0 1 0 0 2 0 1 1 0 4 2 1 1]
 [1 0 1 1 0 0 0 0 2 0 1 0 0 0 1 0 2 0]
 [1 0 0 0 0 0 1 0 1 3 0 0 0 0 1 2 1 0]
 [1 0 1 3 1 0 4 0 1 4 1 0 4 3 1 3 1 5]]
             precision    recall  f1-score   support

        Bug       0.33      0.27      0.30        22
       Dark       0.00      0.00      0.00        12
     Dragon       0.18      0.18      0.18        11
   Electric       0.07      0.08      0.07        13
      Fairy       0.14      1.0

In [17]:
from sklearn.ensemble import RandomForestClassifier

In [18]:
rfc = RandomForestClassifier(n_estimators=200)

In [19]:
rfc.fit(X_train,y_train)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=200, n_jobs=1,
            oob_score=False, random_state=None, verbose=0,
            warm_start=False)

In [20]:
rfc_pred = rfc.predict(X_test)

In [21]:
print confusion_matrix(y_test, rfc_pred)
print(classification_report(y_test, rfc_pred))
print(accuracy_score(y_test, rfc_pred))

[[ 3  0  0  0  0  2  0  0  1  1  0  0  3  2  3  4  1  2]
 [ 0  1  2  0  0  0  2  0  0  1  0  0  3  0  0  0  0  3]
 [ 1  0  0  1  2  0  0  0  0  0  0  0  1  0  1  1  0  4]
 [ 0  0  0  1  0  0  1  0  1  0  0  1  3  0  4  0  0  2]
 [ 0  0  0  0  1  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  1  0  0  0  1  1  0  4  0  0  1  0  0]
 [ 0  1  2  1  0  1  5  0  0  2  0  0  1  0  0  0  0  3]
 [ 0  0  0  1  0  0  0  0  0  0  0  0  0  0  1  0  0  0]
 [ 1  0  0  0  0  0  1  0  2  0  0  0  0  0  3  2  1  2]
 [ 3  0  0  3  0  0  2  0  1  0  0  0  2  1  2  0  0  9]
 [ 0  0  1  0  0  0  0  0  0  1  0  0  5  1  0  2  1  1]
 [ 1  0  0  0  1  0  0  0  0  0  0  0  0  0  0  0  1  5]
 [ 0  1  0  0  0  0  1  0  0  2  0  0 17  0  1  1  1  2]
 [ 0  0  0  0  1  0  0  0  0  0  0  0  3  0  0  0  0  0]
 [ 0  0  0  0  1  0  1  0  0  3  0  1  1  0  4  0  1  6]
 [ 1  0  0  0  0  1  0  0  1  0  0  0  1  0  0  1  2  2]
 [ 2  0  0  0  0  0  0  0  1  2  0  0  0  0  0  2  2  1]
 [ 1  0  1  1  1  0  1  0  0  4

/home/trainman/anaconda2/lib/python2.7/site-packages/sklearn/metrics/classification.py:1074: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


In [51]:
from IPython.display import Image
from sklearn.externals.six import StringIO
from sklearn.tree import export_graphviz
import pydot

In [67]:
features = list(X_test)
features

['Attack', 'Defense', 'Sp. Atk', 'Sp. Def', 'Speed', 'Generation']

In [68]:
dot_data = StringIO()  
export_graphviz(dtree, out_file=dot_data,feature_names=features,filled=True,rounded=True)

graph = pydot.graph_from_dot_data(dot_data.getvalue())  
j = graph.create_png()

dot: graph is too large for cairo-renderer bitmaps. Scaling by 0.571162 to fit



In [69]:
graph.write_jpg(path='test.jpg')

dot: graph is too large for cairo-renderer bitmaps. Scaling by 0.571162 to fit



True