In [36]:
class Window(object):
    """
    Class that generates a sliding window from an array
    """ 
    def __init__(self, vec, size, mode='center'):
        """
        Initiates class Window

        Parameters:
        -----------
        vec : array_like
            list containing labels
        size : int
            size of the window
        mode : string {begin, center,  end}
            point of the target frame
        """
        self.vec = vec
        self.size = size
        self.mode = mode
        self.i = 0
        self.window = []


    def _getBegin(self):
        """
        Return the window with the target in the beginning of the vector.

        Example:
        --------
        >>>vec = ['a', 'b', 'c', 'd']
        >>>Window(vec, 1, mode='begin')._getBegin()
           ['a', 'b'], ['b', 'c'], ['c', 'd'], ['d']
        """
        index = self.i
        window = []
        if index < (len(self.vec) - self.size):
            window.append(self.vec[index:index+self.size+1])
        else:
            window.append(self.vec[index:])
        return window


    def _getCenter(self):
        """
        Return the window with the target in the center of the vector.

        Example:
        --------
        >>>vec = ['a', 'b', 'c', 'd']
        >>>Window(vec, 1, mode='center')._getCenter()
           ['a', 'b'], ['a', 'b', 'c'], ['b', 'c', 'd'], ['c', 'd']
        """
        index = self.i
        window = []
        if index <= self.size:
            window = self.vec[:index]
        elif index > self.size:
            window.extend(self.vec[index-self.size:index])
        window.append(self.vec[index])
        if index >= (len(self.vec) - self.size):
            window.extend(self.vec[index+1:])
        elif index < (len(self.vec) - self.size):
            window.extend(self.vec[index+1:index+self.size+1])
        return window


    def _getEnd(self):
        """
        Return the window with the target in the end of the vector.

        Example:
        --------
        >>>vec = ['a', 'b', 'c', 'd']
        >>>Window(vec, 1, mode='begin')._getBegin()
           ['a'], ['a', 'b'], ['b', 'c'], ['c', 'd']
        """
        index = self.i
        window = []
        if index >= self.size:
            window.append(self.vec[index-self.size:index+1])
        else:
            window.append(self.vec[:index+1])
        return window


    def __iter__(self):
        """
        Iterates over the list of labels, yielding a window of
        size equals to `self.size` each time.

        Yields:
        -------
        i : int
            index of the original list
        vec[i] : {string, int}
            target label in the list at index `i`
        window : array_like
            list containing a subset of the elements of the 
            original list
        """
        for index in range(len(self.vec)):
            self.i = index
            if self.mode == 'begin':
                self.window = self._getBegin()
            elif self.mode == 'end':
                self.window = self._getEnd()
            else:
                self.window = self._getCenter()
            yield self.i, self.vec[index], self.window


    def __str__(self):
        return 'Window of size: %d with target %s [index %d]' % ((self.size+1)*2, self.vec[self.i], self.i)

    
    def updateVec(self, value, index=None):
        """Update `self.vec` with `value`"""
        if index:
            self.vec[index] = value
        else:
            self.vec[self.i] = value


    def mode(self):
        """
        Returns the mode of the window `self.window`. Mode is the value 
        that appears most often in a set of data.
        """
        return stats.mode(self.window).mode[0]

In [37]:
vec = ['a', 'b', 'c', 'd', 'e']
w = Window(vec, 2, mode='center')

for k in w:
    print k

(0, 'a', ['a', 'b', 'c'])
(1, 'b', ['a', 'b', 'c', 'd'])
(2, 'c', ['a', 'b', 'c', 'd', 'e'])
(3, 'd', ['b', 'c', 'd', 'e'])
(4, 'e', ['c', 'd', 'e'])


In [53]:
import numpy as np

X_train = np.ones((10,10))
y_train = np.zeros((10,1))

nb_rows, nb_cols = X_train.shape
X_train = np.append(X_train, y_train, axis=1)

frames = 8
X_new = []
total = frames - (nb_rows % frames)
print total
for k in range(total):
    #X_train.append(X_train[-1], axis=1)
    X_train = np.vstack([X_train, X_train[-1]])

#dim = 0
#for n in range(nb_rows+total):
#    if n % 16:
#        dim += 1
#        X_new[dim].append(X_train[n:])
#    print n

print X_train.shape

6
(16, 11)


In [55]:
k = X_train.reshape((2, 8, 11))
print k

[[[ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  0.]
  [ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  0.]
  [ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  0.]
  [ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  0.]
  [ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  0.]
  [ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  0.]
  [ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  0.]
  [ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  0.]]

 [[ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  0.]
  [ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  0.]
  [ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  0.]
  [ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  0.]
  [ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  0.]
  [ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  0.]
  [ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  0.]
  [ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  0.]]]


In [47]:
def create_matrix(X, frames=16):
    nb_rows, nb_cols = X.shape
    addframes = frames - (nb_rows % frames)
    
    for i in range(addframes):
        X = np.vstack([X, X[-1]])
    nb_dims = X.shape[0] / frames
    X = X.reshape((nb_dims, frames, nb_cols))
    return X
    
X_train = np.ones((10,10))
X3d = create_matrix(X_train, frames=8)

In [56]:
print k.shape

(2, 8, 11)


In [69]:
X = k[:,:,:-1]
y = k[:,:,-1]
nb_dims, nb_rows, nb_cols = X.shape
print nb_dims

2


In [78]:
from keras.datasets import mnist

(X_train, y_train), (X_test, y_test) = mnist.load_data()

15294464/15296311 [============================>.] - ETA: 0s

In [87]:
from keras.utils import np_utils
nb_classes = 10

X_train = X_train.reshape(X_train.shape[0], 28, 28, 1)
X_test = X_test.reshape(X_test.shape[0], 28, 28, 1)
X_train = X_train.astype('float32')
X_test = X_test.astype('float32')
X_train /= 255
X_test /= 255
print('X_train shape:', X_train.shape)
print(X_train.shape[0], 'train samples')
print(X_test.shape[0], 'test samples')

# Converts class vectors to binary class matrices.
Y_train = np_utils.to_categorical(y_train, nb_classes)
Y_test = np_utils.to_categorical(y_test, nb_classes)

row, col, pixel = X_train.shape[1:]


('X_train shape:', (60000, 28, 28, 1))
(60000, 'train samples')
(10000, 'test samples')


In [88]:
print row, col, pixel

28 28 1


In [77]:
for k in X_train:
    print len(k),k
    break

218 [1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 4, 2, 2, 2, 5, 2, 2, 2, 2, 2, 2, 2, 2, 9, 2, 2, 2, 5, 2, 4, 2, 2, 2, 2, 2, 2, 2, 4, 2, 2, 2, 2, 2, 2, 2, 2, 4, 2, 2, 2, 6, 2, 2, 2, 2, 2, 4, 2, 2, 2, 4, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 4, 2, 2, 2, 2, 2, 2, 2, 2, 2, 5, 2, 2, 2, 8, 2, 8, 2, 5, 4, 2, 2, 2, 2, 2, 2, 2, 4, 2, 2, 2, 2, 2, 5, 2, 2, 2, 2, 2, 2, 2, 2, 2, 6, 2, 2, 2, 2, 2, 2, 5, 2, 2, 2, 2, 2, 8, 4, 2, 2, 2, 2, 2, 4, 2, 7, 2, 5, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 7, 4, 2, 2, 2, 2, 2, 4, 2, 2, 2, 2, 2, 2, 2, 2, 2, 6, 2, 2, 2, 4, 2, 2, 2, 2, 2, 2, 2, 5, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 4, 2, 2, 2, 2, 2, 2, 2, 2, 2, 5, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2]


In [30]:
import numpy as np
frames = 5
stride = 5

X = np.ones((12,3))
y = np.ones((12,3))

# fill missing rows
nb_rows, nb_cols = X.shape
addframes = stride - ((nb_rows - frames) % stride)
print 'Adding : ', addframes
for i in range(addframes):
    X = np.vstack([X, X[-1]])
    y = np.vstack([y, y[-1]])
    
print 'Modified shape X: ', X.shape
print 'Modified shape y: ', y.shape

print('building matrix...')
nb_rows, nb_cols = X.shape
nb_dims = 1 + ((nb_rows - frames) / stride)
print 'Divide into dimensions: ', nb_dims
X_total = []
y_total = []
index = 0
for dim in xrange(nb_dims):
    final = index + frames
    X_total.append(X[index:final])
    y_total.append(y[index:final])
    index = index + stride

X_total = np.array(X_total)
print X_total.shape
print X_total

Adding :  3
Modified shape X:  (15, 3)
Modified shape y:  (15, 3)
building matrix...
Divide into dimensions:  3
(3, 5, 3)
[[[ 1.  1.  1.]
  [ 1.  1.  1.]
  [ 1.  1.  1.]
  [ 1.  1.  1.]
  [ 1.  1.  1.]]

 [[ 1.  1.  1.]
  [ 1.  1.  1.]
  [ 1.  1.  1.]
  [ 1.  1.  1.]
  [ 1.  1.  1.]]

 [[ 1.  1.  1.]
  [ 1.  1.  1.]
  [ 1.  1.  1.]
  [ 1.  1.  1.]
  [ 1.  1.  1.]]]
